import type { Metadata } from "next";
import { MantineProvider } from "@mantine/core";

import "./globals.css";
import "@mantine/core/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
